### ISSUE TITLE
failure to swift build

### ISSUE THREAD

**Issue by chad3814** [Zewo/Redis#9]
I'm super new to swift packages, but somewhere here looks like one package depends on open-swift/C7 and a different package refers to it as SwiftX/C7 (but it was moved to open-swift/C7?)

```
Cloning https://github.com/Zewo/Redis
HEAD is now at c842af7 Update README
Resolved version: 0.3.0
Cloning https://github.com/VeniceX/TCP.git
HEAD is now at 9582524 Merge pull request #2 from VeniceX/TCPConnection
Resolved version: 0.4.2
Cloning https://github.com/VeniceX/IP.git
HEAD is now at b37a23c add MIT header
Resolved version: 0.4.3
Cloning https://github.com/VeniceX/Venice.git
HEAD is now at dbb11f3 Merge pull request #18 from VeniceX/double
Resolved version: 0.4.2
Cloning https://github.com/VeniceX/CLibvenice.git
HEAD is now at d7adcd4 add necessary headers for linux
Resolved version: 0.4.2
Cloning https://github.com/open-swift/C7.git
HEAD is now at f6b06f4 Time bug fix
Resolved version: 0.4.2
Cloning https://github.com/Zewo/OS.git
HEAD is now at 1c63284 rename module to operating system
Resolved version: 0.4.2
Cloning https://github.com/Zewo/Data.git
HEAD is now at ed1f085 Merge pull request #2 from Zewo/c7-0-2
Resolved version: 0.4.9
Cloning https://github.com/SwiftX/C7.git
/usr/bin/git clone --recursive --depth 10 https://github.com/SwiftX/C7.git /Users/chad/sfg/Packages/C7
fatal: destination path '/Users/chad/sfg/Packages/C7' already exists and is not an empty directory.

error: Failed to clone https://github.com/SwiftX/C7.git to /Users/chad/sfg/Packages/C7

```

I get this on macOS (xcode 8 beta 2): Apple Swift version 3.0 (swiftlang-800.0.33.1 clang-800.0.31)
and linux: Swift version 3.0 (swift-3.0-PREVIEW-2)

**Comment by Danappelxx** [comment]
Hi! This package hasn't been getting a lot of attention recently, unfortunately. I think your best shot is to either

1) Set the minor version to `0.5` and use the `04-12` snapshot, which should build fine.
2) Use a more up to date Redis client, such as [Redbird](https://github.com/czechboy0/redbird) (which we're actually planning to merge into Zewo, anyway)

**Comment by chad3814** [comment]
only used 0.3 because that's what your README.md said... tried 0.5 and there's a huge list of warnings and errors building C7. Guess I'll go with Redbird.
